// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SampleTech.Api.Data;

#nullable disable

namespace SampleTech.Api.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("SampleTech.Api.Models.AuditLog", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("Email").HasMaxLength(320).HasColumnType("character varying(320)");
            b.Property<string>("EventType").IsRequired().HasColumnType("text");
            b.Property<string>("IpAddress").HasMaxLength(45).HasColumnType("character varying(45)");
            b.Property<string>("Metadata").HasColumnType("text");
            b.Property<DateTimeOffset>("OccurredAt").HasColumnType("timestamp with time zone");
            b.Property<Guid?>("TenantId").HasColumnType("uuid");
            b.Property<string>("UserAgent").HasMaxLength(512).HasColumnType("character varying(512)");
            b.Property<Guid?>("UserId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("OccurredAt");
            b.HasIndex("TenantId");
            b.HasIndex("UserId");
            b.ToTable("AuditLogs");
        });

        modelBuilder.Entity("SampleTech.Api.Models.Claim", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<decimal>("ApprovedAmount").HasColumnType("numeric(18,2)");
            b.Property<Guid>("ClaimantId").HasColumnType("uuid");
            b.Property<string>("ClaimNumber").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
            b.Property<decimal>("ClaimedAmount").HasColumnType("numeric(18,2)");
            b.Property<string>("Description").IsRequired().HasMaxLength(2000).HasColumnType("character varying(2000)");
            b.Property<DateOnly>("IncidentDate").HasColumnType("date");
            b.Property<Guid>("PolicyId").HasColumnType("uuid");
            b.Property<string>("ReviewNotes").HasColumnType("text");
            b.Property<Guid?>("ReviewedByUserId").HasColumnType("uuid");
            b.Property<string>("Status").IsRequired().HasColumnType("text");
            b.Property<DateTimeOffset>("SubmittedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("ClaimNumber").IsUnique();
            b.ToTable("Claims");
        });

        modelBuilder.Entity("SampleTech.Api.Models.Coverage", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("CoverageType").IsRequired().HasColumnType("text");
            b.Property<decimal?>("Deductible").HasColumnType("numeric(12,2)");
            b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
            b.Property<DateOnly>("EffectiveDate").HasColumnType("date");
            b.Property<bool>("IsActive").HasColumnType("boolean");
            b.Property<decimal?>("LimitAggregate").HasColumnType("numeric(12,2)");
            b.Property<decimal?>("LimitPerOccurrence").HasColumnType("numeric(12,2)");
            b.Property<Guid>("PolicyId").HasColumnType("uuid");
            b.Property<decimal>("Premium").HasColumnType("numeric(12,2)");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.ToTable("Coverages");
        });

        modelBuilder.Entity("SampleTech.Api.Models.Insured", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("Address").IsRequired().HasColumnType("text");
            b.Property<Guid?>("AssignedAgentId").HasColumnType("uuid");
            b.Property<string>("BusinessName").HasMaxLength(255).HasColumnType("character varying(255)");
            b.Property<DateOnly?>("DateOfBirth").HasColumnType("date");
            b.Property<string>("Email").IsRequired().HasMaxLength(320).HasColumnType("character varying(320)");
            b.Property<string>("FirstName").HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<string>("LastName").HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<Guid?>("LinkedUserId").HasColumnType("uuid");
            b.Property<string>("Phone").HasMaxLength(30).HasColumnType("character varying(30)");
            b.Property<string>("TaxId").HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<string>("Type").IsRequired().HasColumnType("text");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("TenantId", "AssignedAgentId");
            b.ToTable("Insureds");
        });

        modelBuilder.Entity("SampleTech.Api.Models.MutationAuditLog", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("Action").IsRequired().HasColumnType("text");
            b.Property<Guid?>("ActorUserId").HasColumnType("uuid");
            b.Property<string>("ActorRole").HasMaxLength(50).HasColumnType("character varying(50)");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<Guid>("EntityId").HasColumnType("uuid");
            b.Property<string>("EntityType").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<string>("IpAddress").HasMaxLength(45).HasColumnType("character varying(45)");
            b.Property<string>("NextState").HasColumnType("text");
            b.Property<string>("PreviousState").HasColumnType("text");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<string>("UserAgent").HasMaxLength(512).HasColumnType("character varying(512)");
            b.HasKey("Id");
            b.HasIndex("ActorUserId");
            b.HasIndex("CreatedAt");
            b.HasIndex("TenantId", "EntityType", "EntityId");
            b.ToTable("MutationAuditLogs");
        });

        modelBuilder.Entity("SampleTech.Api.Models.PasswordResetToken", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset>("ExpiresAt").HasColumnType("timestamp with time zone");
            b.Property<bool>("IsUsed").HasColumnType("boolean");
            b.Property<string>("Token").IsRequired().HasMaxLength(512).HasColumnType("character varying(512)");
            b.Property<Guid>("UserId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("Token").IsUnique();
            b.ToTable("PasswordResetTokens");
        });

        modelBuilder.Entity("SampleTech.Api.Models.Policy", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<Guid?>("AssignedAgentId").HasColumnType("uuid");
            b.Property<DateTimeOffset?>("CancelledAt").HasColumnType("timestamp with time zone");
            b.Property<string>("CancellationReason").HasMaxLength(2000).HasColumnType("character varying(2000)");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<DateOnly>("EffectiveDate").HasColumnType("date");
            b.Property<DateOnly>("ExpirationDate").HasColumnType("date");
            b.Property<Guid>("InsuredId").HasColumnType("uuid");
            b.Property<Guid>("IssuedByUserId").HasColumnType("uuid");
            b.Property<string>("LineOfBusiness").IsRequired().HasColumnType("text");
            b.Property<string>("PolicyNumber").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
            b.Property<Guid?>("QuoteId").HasColumnType("uuid");
            b.Property<Guid?>("RenewalPolicyId").HasColumnType("uuid");
            b.Property<string>("Status").IsRequired().HasColumnType("text");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<decimal>("TotalPremium").HasColumnType("numeric(12,2)");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("PolicyNumber").IsUnique();
            b.HasIndex("TenantId", "Status");
            b.ToTable("Policies");
        });

        modelBuilder.Entity("SampleTech.Api.Models.PolicyDocument", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("BlobUrl").IsRequired().HasMaxLength(2048).HasColumnType("character varying(2048)");
            b.Property<string>("ContentType").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("FileName").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
            b.Property<long>("FileSizeBytes").HasColumnType("bigint");
            b.Property<Guid>("PolicyId").HasColumnType("uuid");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<Guid>("UploadedByUserId").HasColumnType("uuid");
            b.HasKey("Id");
            b.ToTable("PolicyDocuments");
        });

        modelBuilder.Entity("SampleTech.Api.Models.Quote", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<DateTimeOffset?>("BindRequestedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("Coverages").IsRequired().HasColumnType("text");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<DateOnly>("EffectiveDate").HasColumnType("date");
            b.Property<DateOnly>("ExpirationDate").HasColumnType("date");
            b.Property<decimal>("Fees").HasColumnType("numeric(12,2)");
            b.Property<Guid>("IssuedByUserId").HasColumnType("uuid");
            b.Property<DateOnly>("QuoteExpiryDate").HasColumnType("date");
            b.Property<string>("Status").IsRequired().HasColumnType("text");
            b.Property<Guid>("SubmissionId").HasColumnType("uuid");
            b.Property<decimal>("Taxes").HasColumnType("numeric(12,2)");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<string>("Terms").HasMaxLength(4000).HasColumnType("character varying(4000)");
            b.Property<decimal>("TotalDue").HasColumnType("numeric(12,2)");
            b.Property<decimal>("TotalPremium").HasColumnType("numeric(12,2)");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.Property<int>("Version").HasColumnType("integer");
            b.HasKey("Id");
            b.HasIndex("SubmissionId");
            b.HasIndex("Status", "QuoteExpiryDate");
            b.ToTable("Quotes");
        });

        modelBuilder.Entity("SampleTech.Api.Models.RateTable", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<decimal>("BaseRate").HasColumnType("numeric(12,2)");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset>("EffectiveFrom").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset?>("EffectiveTo").HasColumnType("timestamp with time zone");
            b.Property<string>("FactorsJson").IsRequired().HasColumnType("text");
            b.Property<decimal>("FlatFee").HasColumnType("numeric(12,2)");
            b.Property<bool>("IsActive").HasColumnType("boolean");
            b.Property<string>("LineOfBusiness").IsRequired().HasColumnType("text");
            b.Property<string>("ProductCode").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<int>("TableVersion").HasColumnType("integer");
            b.Property<decimal>("TaxRate").HasColumnType("numeric(8,6)");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("TenantId", "LineOfBusiness", "IsActive");
            b.HasIndex("TenantId", "LineOfBusiness", "ProductCode", "TableVersion").IsUnique();
            b.ToTable("RateTables");
        });

        modelBuilder.Entity("SampleTech.Api.Models.RefreshToken", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset>("ExpiresAt").HasColumnType("timestamp with time zone");
            b.Property<bool>("IsRevoked").HasColumnType("boolean");
            b.Property<string>("Token").IsRequired().HasColumnType("text");
            b.Property<Guid>("UserId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("Token").IsUnique();
            b.ToTable("RefreshTokens");
        });

        modelBuilder.Entity("SampleTech.Api.Models.Submission", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<Guid?>("AssignedUnderwriterId").HasColumnType("uuid");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("DeclineReason").HasMaxLength(2000).HasColumnType("character varying(2000)");
            b.Property<DateOnly>("EffectiveDate").HasColumnType("date");
            b.Property<DateOnly>("ExpirationDate").HasColumnType("date");
            b.Property<Guid>("InsuredId").HasColumnType("uuid");
            b.Property<string>("LineOfBusiness").IsRequired().HasColumnType("text");
            b.Property<string>("Notes").HasMaxLength(4000).HasColumnType("character varying(4000)");
            b.Property<string>("RiskData").IsRequired().HasColumnType("text");
            b.Property<string>("Status").IsRequired().HasColumnType("text");
            b.Property<Guid>("SubmittedByUserId").HasColumnType("uuid");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("InsuredId");
            b.HasIndex("TenantId", "Status");
            b.ToTable("Submissions");
        });

        modelBuilder.Entity("SampleTech.Api.Models.Tenant", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("LogoUrl").HasMaxLength(2048).HasColumnType("character varying(2048)");
            b.Property<string>("Name").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
            b.Property<string>("Plan").IsRequired().HasColumnType("text");
            b.Property<string>("PrimaryDomain").HasMaxLength(253).HasColumnType("character varying(253)");
            b.Property<string>("Slug").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<string>("Status").IsRequired().HasColumnType("text");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("Slug").IsUnique();
            b.ToTable("Tenants");
        });

        modelBuilder.Entity("SampleTech.Api.Models.User", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("Email").IsRequired().HasMaxLength(320).HasColumnType("character varying(320)");
            b.Property<int>("FailedLoginAttempts").HasColumnType("integer");
            b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<DateTimeOffset?>("LastLoginAt").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset?>("LockedUntil").HasColumnType("timestamp with time zone");
            b.Property<bool>("MfaEnabled").HasColumnType("boolean");
            b.Property<string>("PasswordHash").HasColumnType("text");
            b.Property<string>("Role").IsRequired().HasColumnType("text");
            b.Property<string>("Status").IsRequired().HasColumnType("text");
            b.Property<Guid?>("TenantId").HasColumnType("uuid");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("TenantId", "Email").IsUnique();
            b.ToTable("Users");
        });

        // Relationships
        modelBuilder.Entity("SampleTech.Api.Models.Claim", b =>
        {
            b.HasOne("SampleTech.Api.Models.Policy", "Policy").WithMany("Claims").HasForeignKey("PolicyId");
            b.HasOne("SampleTech.Api.Models.User", "Claimant").WithMany("Claims").HasForeignKey("ClaimantId");
            b.HasOne("SampleTech.Api.Models.User", "ReviewedBy").WithMany().HasForeignKey("ReviewedByUserId");
        });

        modelBuilder.Entity("SampleTech.Api.Models.Coverage", b =>
        {
            b.HasOne("SampleTech.Api.Models.Policy", "Policy").WithMany("Coverages").HasForeignKey("PolicyId");
            b.HasOne("SampleTech.Api.Models.Tenant", "Tenant").WithMany().HasForeignKey("TenantId");
        });

        modelBuilder.Entity("SampleTech.Api.Models.Insured", b =>
        {
            b.HasOne("SampleTech.Api.Models.Tenant", "Tenant").WithMany("Insureds").HasForeignKey("TenantId");
            b.HasOne("SampleTech.Api.Models.User", "LinkedUser").WithMany().HasForeignKey("LinkedUserId");
            b.HasOne("SampleTech.Api.Models.User", "AssignedAgent").WithMany().HasForeignKey("AssignedAgentId");
        });

        modelBuilder.Entity("SampleTech.Api.Models.PasswordResetToken", b =>
        {
            b.HasOne("SampleTech.Api.Models.User", "User").WithMany().HasForeignKey("UserId");
        });

        modelBuilder.Entity("SampleTech.Api.Models.Policy", b =>
        {
            b.HasOne("SampleTech.Api.Models.Tenant", "Tenant").WithMany().HasForeignKey("TenantId");
            b.HasOne("SampleTech.Api.Models.Quote", "Quote").WithOne("Policy").HasForeignKey("SampleTech.Api.Models.Policy", "QuoteId");
            b.HasOne("SampleTech.Api.Models.Insured", "Insured").WithMany("Policies").HasForeignKey("InsuredId");
            b.HasOne("SampleTech.Api.Models.User", "IssuedByUser").WithMany("Policies").HasForeignKey("IssuedByUserId");
            b.HasOne("SampleTech.Api.Models.User", "AssignedAgent").WithMany().HasForeignKey("AssignedAgentId");
            b.HasOne("SampleTech.Api.Models.Policy", "RenewalPolicy").WithMany().HasForeignKey("RenewalPolicyId");
        });

        modelBuilder.Entity("SampleTech.Api.Models.PolicyDocument", b =>
        {
            b.HasOne("SampleTech.Api.Models.Policy", "Policy").WithMany("Documents").HasForeignKey("PolicyId");
            b.HasOne("SampleTech.Api.Models.Tenant", "Tenant").WithMany().HasForeignKey("TenantId");
            b.HasOne("SampleTech.Api.Models.User", "UploadedByUser").WithMany().HasForeignKey("UploadedByUserId");
        });

        modelBuilder.Entity("SampleTech.Api.Models.Quote", b =>
        {
            b.HasOne("SampleTech.Api.Models.Tenant", "Tenant").WithMany().HasForeignKey("TenantId");
            b.HasOne("SampleTech.Api.Models.Submission", "Submission").WithMany("Quotes").HasForeignKey("SubmissionId");
            b.HasOne("SampleTech.Api.Models.User", "IssuedByUser").WithMany().HasForeignKey("IssuedByUserId");
        });

        modelBuilder.Entity("SampleTech.Api.Models.RateTable", b =>
        {
            b.HasOne("SampleTech.Api.Models.Tenant", "Tenant").WithMany().HasForeignKey("TenantId");
        });

        modelBuilder.Entity("SampleTech.Api.Models.RefreshToken", b =>
        {
            b.HasOne("SampleTech.Api.Models.User", "User").WithMany("RefreshTokens").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade);
        });

        modelBuilder.Entity("SampleTech.Api.Models.Submission", b =>
        {
            b.HasOne("SampleTech.Api.Models.Tenant", "Tenant").WithMany().HasForeignKey("TenantId");
            b.HasOne("SampleTech.Api.Models.Insured", "Insured").WithMany("Submissions").HasForeignKey("InsuredId");
            b.HasOne("SampleTech.Api.Models.User", "SubmittedByUser").WithMany().HasForeignKey("SubmittedByUserId");
            b.HasOne("SampleTech.Api.Models.User", "AssignedUnderwriter").WithMany().HasForeignKey("AssignedUnderwriterId");
        });

        modelBuilder.Entity("SampleTech.Api.Models.User", b =>
        {
            b.HasOne("SampleTech.Api.Models.Tenant", "Tenant").WithMany("Users").HasForeignKey("TenantId").IsRequired(false);
        });
#pragma warning restore 612, 618
    }
}
